### ISSUE TITLE
get REST

### ISSUE THREAD

**Issue by susanlie** [PavelPolyakov/etcd-test#1]
Hai Pavel,

How i can use the rest for this project, i want to get the uuid

**Comment by PavloPoliakov** [comment]
hi @susanlie,

I'm not sure I get your point. The goal of the repository is to show a variant of the solution, when new applications can autodiscover each other and form a cluster.
In theory each of the applications can have REST endpoints, or there could be a separate application which provides REST endpoints, while cluster does the calculations.
